node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
//     docker.withRegistry('https://index.docker.io/v2/', 'dockerhub') {
// LOOK AT THIS NEXT LINE
	   docker.withRegistry('https://hub.docker.com/repository/docker/tewks18', 'dockerhub') {
       def app = docker.build("tewks18/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }
}
